version: "3.9"

services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  db:
    image: postgres
    shm_size: 1g
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5003:80"
    depends_on:
      - db
    logging:
      driver: none
  
  metabase:
    image: metabase/metabase:latest
    hostname: metabase
    volumes:
    - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: ${DB_USERNAME}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
